{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import CNN2Head_input\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "import BKNetStyle\n",
    "from const import *\n",
    "import cv2\n",
    "\n",
    "from IPython.display import Image, display"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "sess = tf.InteractiveSession()\n",
    "x = tf.placeholder(tf.float32, [None, 48, 48, 1])\n",
    "\n",
    "y_smile_conv, y_gender_conv, y_age_conv, phase_train, keep_prob = BKNetStyle.BKNetModel(x)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Restore model\n",
      "INFO:tensorflow:Restoring parameters from ./save/current2/model-age101.ckpt.meta\n"
     ]
    },
    {
     "ename": "DataLossError",
     "evalue": "Unable to open table file ./save/current2/model-age101.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save_3/RestoreV2 (defined at <ipython-input-9-c1c514e33bcc>:14)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_3/Const_0_0, save_3/RestoreV2/tensor_names, save_3/RestoreV2/shape_and_slices)]]\n\nCaused by op 'save_3/RestoreV2', defined at:\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n    app.start()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 477, in start\n    ioloop.IOLoop.instance().start()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n    super(ZMQIOLoop, self).start()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 888, in start\n    handler_func(fd_obj, events)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py\", line 440, in _handle_events\n    self._handle_recv()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py\", line 472, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py\", line 414, in _run_callback\n    callback(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 235, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 399, in execute_request\n    user_expressions, allow_stdin)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 196, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2698, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2802, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2862, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-9-c1c514e33bcc>\", line 14, in <module>\n    saver = tf.train.Saver()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 1102, in __init__\n    self.build()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 1114, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 1151, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 795, in _build_internal\n    restore_sequentially, reshape)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 406, in _AddRestoreOps\n    restore_sequentially)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 862, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py\", line 1466, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nDataLossError (see above for traceback): Unable to open table file ./save/current2/model-age101.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save_3/RestoreV2 (defined at <ipython-input-9-c1c514e33bcc>:14)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_3/Const_0_0, save_3/RestoreV2/tensor_names, save_3/RestoreV2/shape_and_slices)]]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mDataLossError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1333\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1334\u001b[0;31m       \u001b[0;32mreturn\u001b[0m \u001b[0mfn\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1335\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mOpError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run_fn\u001b[0;34m(feed_dict, fetch_list, target_list, options, run_metadata)\u001b[0m\n\u001b[1;32m   1318\u001b[0m       return self._call_tf_sessionrun(\n\u001b[0;32m-> 1319\u001b[0;31m           options, feed_dict, fetch_list, target_list, run_metadata)\n\u001b[0m\u001b[1;32m   1320\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_call_tf_sessionrun\u001b[0;34m(self, options, feed_dict, fetch_list, target_list, run_metadata)\u001b[0m\n\u001b[1;32m   1406\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_session\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0moptions\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeed_dict\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfetch_list\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mtarget_list\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1407\u001b[0;31m         run_metadata)\n\u001b[0m\u001b[1;32m   1408\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mDataLossError\u001b[0m: Unable to open table file ./save/current2/model-age101.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[{{node save_3/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_3/Const_0_0, save_3/RestoreV2/tensor_names, save_3/RestoreV2/shape_and_slices)]]",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mDataLossError\u001b[0m                             Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-9-c1c514e33bcc>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Restore model'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     14\u001b[0m \u001b[0msaver\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtrain\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSaver\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 15\u001b[0;31m \u001b[0msaver\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrestore\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msess\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mSAVE_FOLDER2\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m'model-age101.ckpt.meta'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     16\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'OK'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     17\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\u001b[0m in \u001b[0;36mrestore\u001b[0;34m(self, sess, save_path)\u001b[0m\n\u001b[1;32m   1544\u001b[0m       \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1545\u001b[0m         sess.run(self.saver_def.restore_op_name,\n\u001b[0;32m-> 1546\u001b[0;31m                  {self.saver_def.filename_tensor_name: save_path})\n\u001b[0m\u001b[1;32m   1547\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0merrors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mNotFoundError\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0merr\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1548\u001b[0m       \u001b[0;31m# There are three common conditions that might cause this error:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m    927\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    928\u001b[0m       result = self._run(None, fetches, feed_dict, options_ptr,\n\u001b[0;32m--> 929\u001b[0;31m                          run_metadata_ptr)\n\u001b[0m\u001b[1;32m    930\u001b[0m       \u001b[0;32mif\u001b[0m \u001b[0mrun_metadata\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    931\u001b[0m         \u001b[0mproto_data\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtf_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mTF_GetBuffer\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mrun_metadata_ptr\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_run\u001b[0;34m(self, handle, fetches, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1150\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mfinal_fetches\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mfinal_targets\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mhandle\u001b[0m \u001b[0;32mand\u001b[0m \u001b[0mfeed_dict_tensor\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1151\u001b[0m       results = self._do_run(handle, final_targets, final_fetches,\n\u001b[0;32m-> 1152\u001b[0;31m                              feed_dict_tensor, options, run_metadata)\n\u001b[0m\u001b[1;32m   1153\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1154\u001b[0m       \u001b[0mresults\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m[\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_run\u001b[0;34m(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)\u001b[0m\n\u001b[1;32m   1326\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mhandle\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1327\u001b[0m       return self._do_call(_run_fn, feeds, fetches, targets, options,\n\u001b[0;32m-> 1328\u001b[0;31m                            run_metadata)\n\u001b[0m\u001b[1;32m   1329\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1330\u001b[0m       \u001b[0;32mreturn\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_do_call\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_prun_fn\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mhandle\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfeeds\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfetches\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py\u001b[0m in \u001b[0;36m_do_call\u001b[0;34m(self, fn, *args)\u001b[0m\n\u001b[1;32m   1346\u001b[0m           \u001b[0;32mpass\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1347\u001b[0m       \u001b[0mmessage\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0merror_interpolation\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minterpolate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmessage\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_graph\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1348\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0mtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnode_def\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mop\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mmessage\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1349\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1350\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0m_extend_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mDataLossError\u001b[0m: Unable to open table file ./save/current2/model-age101.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save_3/RestoreV2 (defined at <ipython-input-9-c1c514e33bcc>:14)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_3/Const_0_0, save_3/RestoreV2/tensor_names, save_3/RestoreV2/shape_and_slices)]]\n\nCaused by op 'save_3/RestoreV2', defined at:\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py\", line 16, in <module>\n    app.launch_new_instance()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py\", line 658, in launch_instance\n    app.start()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py\", line 477, in start\n    ioloop.IOLoop.instance().start()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py\", line 177, in start\n    super(ZMQIOLoop, self).start()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py\", line 888, in start\n    handler_func(fd_obj, events)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py\", line 440, in _handle_events\n    self._handle_recv()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py\", line 472, in _handle_recv\n    self._run_callback(callback, msg)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py\", line 414, in _run_callback\n    callback(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py\", line 277, in null_wrapper\n    return fn(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 283, in dispatcher\n    return self.dispatch_shell(stream, msg)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 235, in dispatch_shell\n    handler(stream, idents, msg)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py\", line 399, in execute_request\n    user_expressions, allow_stdin)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py\", line 196, in do_execute\n    res = shell.run_cell(code, store_history=store_history, silent=silent)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2698, in run_cell\n    interactivity=interactivity, compiler=compiler, result=result)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2802, in run_ast_nodes\n    if self.run_code(code, result):\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py\", line 2862, in run_code\n    exec(code_obj, self.user_global_ns, self.user_ns)\n  File \"<ipython-input-9-c1c514e33bcc>\", line 14, in <module>\n    saver = tf.train.Saver()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 1102, in __init__\n    self.build()\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 1114, in build\n    self._build(self._filename, build_save=True, build_restore=True)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 1151, in _build\n    build_save=build_save, build_restore=build_restore)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 795, in _build_internal\n    restore_sequentially, reshape)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 406, in _AddRestoreOps\n    restore_sequentially)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py\", line 862, in bulk_restore\n    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py\", line 1466, in restore_v2\n    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py\", line 787, in _apply_op_helper\n    op_def=op_def)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py\", line 488, in new_func\n    return func(*args, **kwargs)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 3274, in create_op\n    op_def=op_def)\n  File \"/Users/jamaalhay/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py\", line 1770, in __init__\n    self._traceback = tf_stack.extract_stack()\n\nDataLossError (see above for traceback): Unable to open table file ./save/current2/model-age101.ckpt.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?\n\t [[node save_3/RestoreV2 (defined at <ipython-input-9-c1c514e33bcc>:14)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](_arg_save_3/Const_0_0, save_3/RestoreV2/tensor_names, save_3/RestoreV2/shape_and_slices)]]\n"
     ]
    }
   ],
   "source": [
    "PATH = 'genki4k/files/file0480.jpg'\n",
    "img = cv2.imread(PATH)\n",
    "img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "img = cv2.resize(img,(48, 48))\n",
    "\n",
    "img = (img - 128) / 255.0\n",
    "T = np.zeros([48, 48, 1])\n",
    "T[:, :, 0] = img\n",
    "test_img = []\n",
    "test_img.append(T)\n",
    "test_img = np.asarray(test_img)\n",
    "\n",
    "print('Restore model')\n",
    "saver = tf.train.Saver()\n",
    "saver.restore(sess, SAVE_FOLDER2 + 'model-age101.ckpt.meta')\n",
    "print('OK')\n",
    "\n",
    "display(Image(filename = PATH, width=100, height=100))\n",
    "\n",
    "predict_y_smile_conv = sess.run(y_smile_conv, feed_dict={x: test_img, phase_train: False, keep_prob: 1})\n",
    "predict_y_gender_conv = sess.run(y_gender_conv, feed_dict={x: test_img, phase_train: False, keep_prob: 1})\n",
    "predict_y_age_conv = sess.run(y_age_conv, feed_dict={x: test_img, phase_train: False, keep_prob: 1})\n",
    "\n",
    "smile_label = \"No \" if np.argmax(predict_y_smile_conv)==0 else \"Yes \"\n",
    "gender_label = \"Female \" if np.argmax(predict_y_gender_conv)==0 else \"Male \"\n",
    "argmax_predict_age = np.argmax(predict_y_age_conv)\n",
    "if argmax_predict_age==0:\n",
    "    age_label = \"Young (age < 30yrs) \"\n",
    "elif argmax_predict_age==1:\n",
    "    age_label = \"Middle (30 <= age <45) \"\n",
    "elif argmax_predict_age==2:\n",
    "    age_label = \"Old (45 <= age < 60) \"\n",
    "else :\n",
    "    age_label = \"Very Old (60 <= age) \"\n",
    "\n",
    "print('Smile: ' + smile_label + str(predict_y_smile_conv))\n",
    "print('Gender: ' + gender_label + str(predict_y_gender_conv))\n",
    "print('Age: ' + age_label + str(predict_y_age_conv))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Restore model\n",
      "INFO:tensorflow:Restoring parameters from ./save/current/model.ckpt\n",
      "OK\n"
     ]
    },
    {
     "data": {
      "image/jpeg": "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAC+AL0DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDzH+12A+5Tl1dh261QdHjz5kLr9RVm2028uoWmgtZJI1+8wHSuQ15pG9Ya2pwHYgdOavzpZ3UJdZgH9DXK2V1ErAOv4YrRmlDYEYCj1pW1LT0ILmURsQGFVC653AjNPvbZ5F356VlfNnGaqxDZqLNuOGIq1E4ToRWGHYd6csjH+LFFhKR2unamiYZmUMtbQukvlyG+bFebReZv+VufrWrZSXyTo0ZJ2nOM9alo0UrnT3G6PKkc1lTM5zg1qz6lJewBZbby2HXHOayLhhkgmpKIC5yBTycj39KhLjPtSGT6UwILjlTWPN941rTn5TWRKfmNNESIT1p46UzvT+1NkRGMaaKVqQU0S9xw60/PFRjrTj0pMpMaTTc5pTQBVIh6nb+L9yamY8LtPPAr0LwBpkGo+EZYkbY/IbFcH4tIbU5Cxxx6V6L8HXaXTL5R0DDGfcVD3Nntc8avtOfT9WngHzbZSucU+6tLiKBZSSMnpWt4ht5YfFlzvyR55OPxrofEkFs3hCCZEUTAjnFDdgijC0XR49R0t5ribDZxgVyep2Ztb6SJCSoPBrsNCn26bIhH8Wa5fUJlGoTKecnireiJauQ6ZpFzqt3Ha2+PNc4ANa83gu+t7iWOWWOMRjJLnGf1qDw/ro0HVFvvJE5VSAmcAn3qpqurXes6hNeXr7pJG+7nCqPQCi+hNlcm0nTrOe4mF/qsVlFEudzAsWPoAOtWrS7s7K6bN2Z41OFYRkFvwNYA25GScelObbHjaSPxqSk7HYNrdlMMJJj2YYNVJ5VkGUIP0rmPNIwcn8KetxIDjcQvU570uUr2nc1y2Dj86N9UYrppG+ZePUVOW2/0pFXHyuCpFZcv3jVx3O2qMh5poiTI+9O7U2l7VRKGmmilPSgUyOo4daVuBQKaxpFdBO9OFNFKaYjvfFqFL9izYY9q9B+CKkRakuc/drgfGUIGqMw5b616J8EovLttSY/eJWp+0ay+E4nxdEq+LLs+lwRWh4mjx4LVgvOV5rL8cSNH45vkx8v2it7xCA/w93Z5AFEnohI4jRJT5Eq9QBk1y95Isl3I4OecVfXVGsbGaCHHmTcMx6gdxWOT06+lUTJjwcZOOoxTd3eg8jFOEbMyooyT6UidWAycUMpI5zkmtGHS5pI920rtGTxV2Lw9cybSQdrenas3UiupsqE30MQxfKeT0pyQFyoznNdTB4Uup5Rtt5Nh4BYYrY/4QW5jjzGgaQ9CWwB+FQ68UarCy6nBpGxzHgnsOK0fskqWqvIjBcYzjO2vRNP8DpBYk3DA3DEcjtXT2nhyyls0s5YyRjlhgHPrWTxGuhoqCS1Z4PIhXcD27iqTjmux8ZeHLjQNTMMiny2XKSdnHY/XGK45+tdMXdXRyTVnYYetL2pDRVkDTQKDSCmT1JRjFRnrTj0pKSKYDgUnWinKM0ybnofjlTHqg2nqK7z4JS7hqEZOThT/AErz7x3IrallT/DXafA1839+PWJSfzqftGr+E5fx3tHxFvBJ9z7QM/lW9rqb/A0ixqdgwc4rD+Iu3/hPb4Hj94vP4Cu1vBbR/CuaRnBfyuh9aUtgR4FMMyMajxgnPapCSW+ppZhuPGOTTRDRGDlhW94fslvL0A457ViEBU4HNbvhq58i7QqMsTUVfh0NaCXOrnokOkwxnJUEeh4xV+ONFHyRrkdzwKQSedCrjjPbtUBIdvmLsOwHSvMfmeqjVt7lVxk7sddorQiuYz3P4rWBE80XJKBfTrWhE0nDLNER6YIqlYTRoGeMj7wz3xToZyZAUjOB/ETVZUdiSVX8G4/lViJS/LY+goJaE8aaRFrvhZ1Mame3TzIyOuB1H+fSvnOddkjKeoJzX0fca7Y6XsW5favQ5714F4ntYbTxDew20gkt/M3RMOhVuR/OuvDyvocNeFlcxiaDS49KXFdRzWGYo6U6igLAKQ0UoGaBNje9SKKYQRTwCRxTJOs8Wq/28ANuAFd18CGb+19QB6GEfzrhvE/F93DYFd18D3xrV4vYw/1qb6m0loc/8Sm8vx5ekdd6/wAhWvqMm/wDKTnlemayfiiv/Fd3h9WU/oK1rld/gCUD+5Uy2HE8k3fNz68e1LjLErj0yaSRNrkU5QAoOR9Kogc0amPOeV6+9a+goPtSfLjPcnpWUg3tz+XtW/oto8tyuBhBz61lUdonRRjeVzvYXKwKBggdDSsWQEsQD1yegFNgwihcjj9KwPEOoSFfssD4J5dvauBK7sei3ZFufxHplqSsjGVu+OabF470uMhBDMP+AiuasvDP2n57ify0PfOM1o3HhTToogySyEnozAgGujlprcwvVex22n+K7K+2i2cNnjB4pNW1y4sLR5ETnOBj1rzm2hfTL6N41OAcjFelW0lvq+n+W6hZWAIOOjDvWU7RZpFO2pw8ei63rl0by8uvIVjuAduR+FU/GGgvpNlp8zTpcCUsBKh9MHH6/rXQ6kur2bsy2sck+7Gxv4RjhgDweRWf4xh1Cbw5Zz3ioI1lBD+TtO5kBYZHB5BxW8JO6fQ56sVZpHn+aOtKRSdK6jhEIpMUuacgyaBCIhY1ft7IsNxqsHEZz1qb7cQmFNFykl1IrmHYeKiXgU9pi/Wk4NO5LR13ihlkv8hh0rtPgvx4huAv3TDx+dcPrqBrwBe45Ndr8HGKeKZEySDAR+tR9o1l8JkfE8n/AITm647qf0rYnAbwJOQMfLWN8VWK+O7nHTC/yrVXL/Dy6I67DzSewk9DzW30PUdUmkks7ZpEGMuSFUfiajvNIvtNQm8tmX0ZfmH5iuit0NzpWlQLKUhZyrgHHzluf6Vsy2s9vetZz/vrR1OC56EDpmsHXaZ3LCQcU76s85jyM88+1d34NjQxPuOX96xNY0PZG15ZgmIcso6j1rR8Ly+VcJGvVuTjkfnRUmpwuiaVOVOdmdiU2vu52jkkVzV9JEJmlZCFzxuHWukuCjgqQDkd+lUxpcG5ZejnpxXLF2OqxzJvbq7craqYnxgSSr+ij+tXLbTLt7SY6lO5nk2+Wdx+UDPAHvn9K6OLR/Pbm6lx7PjP6Vb/ALLgtYyEjGe7Hqa1VTSyIcdbnKfY8yRR/MVQYLN1Nb9vmAKIxk9jUNzHFBMinLyt0UdhVmGOSHEksqqB68VlJ3NbaGqY11GBIrncjr910bBqbxNoi6h8PNQsk3yTWy/aY9zFiSvJx+G6shNct47kIn7xf4iDXXaRq1leS29rvCPLuwR128AZ/WnTTTMKqbR80OfmP1qPNbfi7RjoHijUdMyxW3mYIx7oeVP5EVhE16a1R5UnZ2HKM0/OOKjQ4FGcmmJMViaB0pDSigBw+tSIDzxUNPBOKTKTOv1xWWfCDBNdV8H3kTxadxBBiYVymqTpJNkt8wrpPhVMo8YKAflKNUfaNpfCVvisdvjm5J5BVf5Vq2cgfwDdLjjYeM+1ZHxX58ZzkHJ2LVrTZd/ga9znKoR+lD1RCOW0ac4msXbarsHjb+5IDwa3fEU0l7p6TqGUuASQeAw6/rXG2M5jvMuDj0rrbO+W9tJ4kh89I2/eRA4YD+8KwrQt7x34Wope4yzoU/naZJ5m0skm1sjqcDt+dCypaSHyo1ReRhRRdW1vYSK1lLsibHnROckEe9Vw/wBpTzFOMEgiubqdDRpx3m84OMYq3C/mHO49KyYvlXgZI45FWBKyfNkdKm2o73NeG58qUYb8DTrjVESNmOMiuelvcAsM+lU5bqR4iB1PSrincHa1xt3czz3QuYpmjlRsqao3kl5fkm4upGyeVXgUiTKP9ZJgg881btruESDajynPAVc5rayRnrLRCeG9EMmpqk+9bdzhirHcRnpzXot5pkFnf2S226JXTMRznDr/AJFc3ps9y8ihLPyxkcy/KOtbWrTalFr0bztFJawAeV5S4A6c0nruQ4yg1ZmH8QtHN94ikvtvzXMMbn67QP6V5vqGlTWuTtOK9/1zT0vDbzqOPJUf/WrkPFGjR/YZHCjO30reEmjgnGMjx1RxijBqRl2yMp7Gg4xW5zpEeeKUGgjNJjFMBc04HNNHWpUhaQfKOlJ6blRTex0WpxhgJONx611XwwjWPxRCR/dNcpqhjMgMbHBFdB8N7nyfE8LO4CkEZNZvc3lsP+KvHjKU/wB6MVLow3eDb7ngqf5VU+KMwm8XSMpyoQDIpulXqReE7uEuAzKcAn2xQ9iInJwI63H49ane7uNI1SO5tmw4HPow7g02JjuwOtUb12+0HzDk+9Naqw2+XVHbW/iGzvtoMbCZ8/u8ZyevFNljntbprhlxHJ99D/D6GuV8NWMms+KtLsQW/fXUanb1C5y36A16Fq1t5M9zbYwIpHiwfQE4/pXJWpqDVup30MQ6yafQqRuAR05FLIwYY/Ws+OV1TB7UhnyTzWVjW5LMgBXuM9M0hij5ySD0qJrpQuM4qnJdSSP8pyK0iiZMWPTQkpl8syc9zVwXU0TYjh2Y7BRxSRXW1Ap6/WrUUyM481htJ5NVq9RKdlZE9g80kyySSnIOcGuytrhLm8SNwdpxk4zxXOrNawn9yA2By2OlbGkzrdXKGPLkD5n7AelFrsipLS53Nla+bp6K2CwTmuO8YBYLaRH4yMV2umTHZyeK4/4j2kj2TTR/w1rY4YP3tTwS8x9rfHTNR7SRTmV5bgjGXZsACvR/Dvw6a+tEluX2lhnGa2bsiIrmbPNdppMGvaH+FcAX5JDmsDUvhxd2oLRjevsKn2nkWqSezPOUiZiMda6TRNN86CQkdCO31rY03wgzTYkVgR2PFb1rof2BpIxkqSMVjUqcysjsw9H2buzz+/vNlyAsQ29MV1HgK3S98QxQuAFYHp1rlLxoFUM0i7vTNT6L4oOh6hFdw24lZM4VzgGt2rvQ43K17m34/tE0nxLJBGxlBAb5uSKpwSaadDle5nSOUD5UzyT9KxPEXiS98S6m97e7Fc8BYxgKKxicn3p8hn7WxpHVNgJiUbuxNUHkeVi8hyx70yiqSSIc29z0n4K6fHc+MpbqTBNnavIg/wBpiF/kxr0DxzojI76lbw70f/W7RyrdM/TiuB+C0/leMJ484Etoy/qD/SvepUDqykBlPBBGQR6H1rKrDn0NqNR03dHz1zFJ8ynnj2qtOB1HH0r07xF4CExafSGVG6m2kPyn/dP8P06fSvMtStbrT52t7u3e3mHGxxg/h2P1rn5Gtz0I1Yz2MuW42Eg5qH7Yy5x8uaJg7MQBk96rPE45YVokjGTkT/2hg88+prT0Kx1LxHqMVhp8PmTSHqThVHqT2FU9K0K81a8jt7eFnd+yqSf/ANXvX0V4F8I2/hqxB2q13IB5jqc7R/dBrWME9jKU3FangXiSPU/C+sXGkXhjaaELukjYlCGUNkZAJ4I/Wum8KeJrUwRWVx5dvJgFZPuq/wBT61rfHnSYvtWn6tE0Rcr9mlUMN2RkqSOvcj8BXksb77UDuOlVyJGPtJN6n0ppsrlFIxtIzkf41T8byInh+Z5B0XivA9N8S6vojh9Pv5oVzym7cv8A3ycj9K3NW+JOp61o7WF9BbsSMebGCp/Ecj8sVPILmVzjjceVdeamMhsiujh+IGsW8KxQuiqK5RlJpvStbGXM0dzB8T9ciI3MjY7HNdXoXxYt55Fi1OLyw3BftXjdKGwaLBzM+oJLSz1G2S9s2QkjcpU/ernLpwsmJCAfpXmHhfxve6DGbUuXtWOQpP3T7Vc1jxqbq5EkfAxzXNUpO/undQrLl95nDE8560meaSiuk88UmkoooAWiiigZ2/wqultfHlkGOBMGj/MZ/pX0qEyQMdeK+QNIvZNO1W1vIj+8glWRfwNfWlhfx39rb3cR/dzxrKhHcHFTIuOx5sPjNponeDUdIuYHRyhMUqydDjuFqS68eeCdeg+z30hCHotzARtP1GcfnXknjSx/srxjq9mudqXTlcnnaTuH6EVz4k9f0qlawrtM9Z1Xwz4cWFbvSvE+npHI2FjuJxgfj1H4g1l2lj4at78DV/EVmYwf+XNXlz9TtGB78153vJ5H1yKDuzyp4qfZxvc1WIqJWPSLv4mQ6QJLTwjp8dpF3vLld8z++Og/WuS1HxXrmrMTf6rd3AP8Lynb+Q4FYIJ+tKDk1e2xg5Nu7LSyNOJVYsfkLdT2IP8ASkgb92RmrGkQefeTIOcWlw35RMf6VSiOPpSZSJGAJPvUPTipm9ahb72aEEgzRmkpKCRcA9OKQrRRk0AIDg0uT2NOXDEA4HvTDwSDTAKO9JQOtAhe9FHeikAtFJS0DFU7WDdgcmvovwFqROirYMxL2482EesZ6j8M/r7V8517H4UvHtrDS9Sjy2xF8wDoykYYVM1oaU9box/jJpPkeKItVjXMGoQqd/bzEG1h+W2vNViZ3CKCWY7QB1J9q+gvHekTeKdLt7K1aONYXEySOueoII/I/pWd4V+HUGloZJl824YYM7rjavoo7fWnBXQpLUz/AIceANOu9EGs6jEtzJOWSOJx8sQBx09aseMPh5YCya606AROnVF6V6J4WsUs9BeCMYQXEm36Zq29uJFZGGQeCD0rXRoXws+XLjSWJIQFZAccjgmqY028LSgWsxMX+s2xlgvpkgcV9FXvw/0+9dnAETN6DNanhjRrzw9cm2ZjJbSD5WX+H61mk1oXLlauj598IWYl1DUd45j0u7Yf9+yP61zSngfpX1H8RSIPBeqyxRx+esRVm2jJU8HnGe9fLp4NUzMfnIprdaKQ1IDTSUtJTJDNLmkooAO9Ol+8D6qDTRyakmHyxn/ZoH0IqBRS0CCiiigApaSgUgFr3T4XQR3vhGLcFYxSPGcj3z/IivC+4+tey/Ba4ZrHUbfJ2pKsg/4ECP8A2UU0rlJ2PWobWCCPhFz16VBcyEq7Y4AqdiSophjDRkGnayGP8PRkaMA3XzGzVvyMkntRpvyWTgcbXb+lTxnMYbcxLDJB7UR2GyDbhhVpfu1C4+apIzTEcN8VrkweErrGcSKEP0r5o/nX0t8W4w3gm5Y9V2/zx/WvmnvUsGFB6UUmeKRIlJRmimIKDRSGgBR1H1qWUHy4/wAahFWgNyKD2oGtj//Z\n",
      "text/plain": [
       "<IPython.core.display.Image object>"
      ]
     },
     "metadata": {
      "image/jpeg": {
       "height": 100,
       "width": 100
      }
     },
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Smile: Yes [[ 0.00149914  0.99850082]]\n",
      "Gender: Male [[ 0.24222387  0.75777608]]\n",
      "Age: Middle (30 <= age <45) [[ 0.11998766  0.42773849  0.35627618  0.09599768]]\n"
     ]
    }
   ],
   "source": [
    "PATH = '/home/ubuntu/coding/cnn/datasets/imdb_crop/00/nm0000100_rm3653409024_1955-1-6_2003.jpg'\n",
    "img = cv2.imread(PATH)\n",
    "img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)\n",
    "img = cv2.resize(img,(48, 48))\n",
    "\n",
    "img = (img - 128) / 255.0\n",
    "T = np.zeros([48, 48, 1])\n",
    "T[:, :, 0] = img\n",
    "test_img = []\n",
    "test_img.append(T)\n",
    "test_img = np.asarray(test_img)\n",
    "\n",
    "print('Restore model')\n",
    "saver = tf.train.Saver()\n",
    "saver.restore(sess, SAVE_FOLDER + 'model.ckpt')\n",
    "print('OK')\n",
    "\n",
    "display(Image(filename = PATH, width=100, height=100))\n",
    "\n",
    "predict_y_smile_conv = sess.run(y_smile_conv, feed_dict={x: test_img, phase_train: False, keep_prob: 1})\n",
    "predict_y_gender_conv = sess.run(y_gender_conv, feed_dict={x: test_img, phase_train: False, keep_prob: 1})\n",
    "predict_y_age_conv = sess.run(y_age_conv, feed_dict={x: test_img, phase_train: False, keep_prob: 1})\n",
    "\n",
    "smile_label = \"No \" if np.argmax(predict_y_smile_conv)==0 else \"Yes \"\n",
    "gender_label = \"Female \" if np.argmax(predict_y_gender_conv)==0 else \"Male \"\n",
    "argmax_predict_age = np.argmax(predict_y_age_conv)\n",
    "if argmax_predict_age==0:\n",
    "    age_label = \"Young (age < 30yrs) \"\n",
    "elif argmax_predict_age==1:\n",
    "    age_label = \"Middle (30 <= age <45) \"\n",
    "elif argmax_predict_age==2:\n",
    "    age_label = \"Old (45 <= age < 60) \"\n",
    "else :\n",
    "    age_label = \"Very Old (60 <= age) \"\n",
    "\n",
    "print('Smile: ' + smile_label + str(predict_y_smile_conv))\n",
    "print('Gender: ' + gender_label + str(predict_y_gender_conv))\n",
    "print('Age: ' + age_label + str(predict_y_age_conv))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
